name: CI

on:
  pull_request:
    types:
    - closed
    branches: 
    - master

  workflow_dispatch:

jobs:
  release:
    name: auto_release
    if: github.event.pull_request.merged == true
    uses: GagMirz/semver-action/.github/workflows/release-update.yml@master
    secrets: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      asset_creation_script: |
        # OLD_TAG_SED_DOT="${OLD_TAG//./\\.}" 
        # OLD_TAG_SED_DASH="${OLD_TAG//./\\-}"
        # NEW_TAG_SED_DOT="${NEW_TAG//./\\.}"
        # NEW_TAG_SED_DASH="${NEW_TAG//./\\-}"
        
        # files_to_update="some.xml after.xml"
        # files_to_rename="rename-me.sh rename-me-too.sh" 
        
        # for file in $files_to_update; do
        #   echo "Updating semver occurrences in $file"
        #   sed -i "s/${OLD_TAG_SED_DOT}/${NEW_TAG_SED_DOT}/g" $file
        #   sed -i "s/${OLD_TAG_SED_DASH}/${NEW_TAG_SED_DASH}/g" $file
        #   git add $file
        # done

        # git config user.name github-actions
        # git config user.email github-actions@github.com

        # git commit -m "Updated xml"
        # git push origin ${{ github.event.repository.default_branch }}

        # for old_name in $files_to_rename; do
        #   echo "Renaming and adding semver to $old_name"
        #   new_name=$(sed "s/\./-$NEW_TAG_SED_DASH./" <<< $old_name)

        #   mv $old_name $new_name
        # done

        # zip -r asdf.zip ./*
        echo "FILES=""" >> $GITHUB_ENV
      post_script: |
        'echo  ${{ secrets.SLACK_WEBHOOK_URL }}'
