name: CI

on:
  pull_request:
    types:
    - closed
    branches: 
    - master

  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: GagMirz/semver-action/.github/workflows/release-update.yml@master
