name: CI

on:
  pull_request:
    types:
    - closed
    - opened
    - synchronize
    branches: 
    - master

  workflow_dispatch:

jobs:
  release:
    name: auto_release
    uses: GagMirz/semver-action/.github/workflows/release-update.yml@master
    secrets: inherit
    with:
      asset_creation_script: |
        touch a.sh
        touch b.sh
        echo "FILES="a.sh b.sh"" >> $GITHUB_ENV
