name: CI

on:
  pull_request:
    types:
    - closed
    branches: 
    - master

  workflow_dispatch:

jobs:
  release:
    name: auto_release
    if: github.event.pull_request.merged == true
    uses: GagMirz/semver-action/.github/workflows/release-update.yml@master
    secrets: inherit
    with:
      asset_creation_script: |

        echo "FILES=""" >> $GITHUB_ENV
