name: CI

on:
  pull_request:
    types:
    - closed
    branches: 
    - master

  workflow_dispatch:

jobs:
  release:
    name: auto_release
    if: github.event.pull_request.merged == true
    uses: GagMirz/semver-action/.github/workflows/release-update.yml@master
    with:
      asset_creation_script: |
        zip -r entry.zip entrypoint.sh
        zip -r stuff.zip some_stuff.sh
        echo "FILES="stuff.zip entry.zip new.zip"" >> $GITHUB_ENV
      files_to_update: >
        some.xml
        after.xml
      files_to_rename: >
        rename-me-0-0-1.sh
        rename-me-too-0-0-1.sh
