name: CI

on:
  pull_request:
    types:
    - closed
    branches: 
    - master

  workflow_dispatch:

jobs:
  release:
    name: auto_release
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: GagMirz/semver-action/.github/workflows/release-update.yml@master
    with:
      asset_creating_script: |
        zip -r asf.zip entrypoint.sh
        echo "FILES=`pwd`/asf.zip" >> $GITHUB_ENV'

